apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-nginx-app-nginx-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./develop/services/nginx-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  postBuild:
    substitute:
      service_name: "nginx-app"
