apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - generated.yaml
patches:
  - target:
      kind: CronWorkflow
    patch: |-
      - op: replace
        path: /spec/suspend
        value: true
  - target:
      kind: CronWorkflow
      labelSelector: bulk-update-cronworkflow-status/sandbox=false
    patch: |-
      - op: replace
        path: /spec/suspend
        value: false
