---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: services-nginx-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./k3d/services"
  prune: true
  sourceRef:
    kind: GitRepository
    name: generated-manifests
  targetNamespace: default
  postBuild:
    substitute:
      service_name: nginx-app
