name: bulk-update-cronworkflow-status

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project name"
        required: true
        type: choice
        options:
          - sandbox

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Create kustomization.yaml in services directories
        run: |
          for dir in services/*; do
            if [ -d "$dir" ]; then
              cat <<EOF > "$dir/kustomization.yaml"
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - generated.yaml
          patches:
            - target:
                kind: CronWorkflow
              patch: |-
                - op: replace
                  path: /spec/suspend
                  value: true
            - target:
                kind: CronWorkflow
                labelSelector: bulk-update-cronworkflow-status/${{ github.event.inputs.project }}=false
              patch: |-
                - op: replace
                  path: /spec/suspend
                  value: false
          EOF
            fi
          done
      - uses: int128/update-generated-files-action@v2
        with:
          token: ${{ steps.token.outputs.token }}
          draft: true
          title: 'chore: bulk update cronworkflow status'
          body: |
            #### Which issue(s) this PR fixes

            - *Please rewrite this.*

            #### What this PR does / why we need it

            - *Please rewrite this.*

            #### Description of changes

            - This PR was generated by bulk-update-cronworkflow-status.

            #### Reveiew points

            - *Please rewrite this.*

            #### Relations

            - *Please rewrite this.*
          labels: |
            bulk-update-cronworkflow-status
          commit-message: 'chore: generate manifests by bulk-update-cronworkflow-status'
