name: bulk-update-cronworkflow-status

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project name"
        required: true
        type: choice
        options:
          - sandbox

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Create kustomization.yaml in services directories
        run: |
          for dir in services/*; do
            if [ -d "$dir" ]; then
              cat <<EOF > "$dir/kustomization.yaml"
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
            - generated.yaml
          patches:
            - target:
                kind: CronWorkflow
              patch: |-
                - op: replace
                  path: /spec/suspend
                  value: true
            - target:
                kind: CronWorkflow
                labelSelector: bulk-update-cronworkflow-status/${{ github.event.inputs.project }}=false
              patch: |-
                - op: replace
                  path: /spec/suspend
                  value: false
          EOF
            fi
          done
