name: Sync FluxCD Manifests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-manifests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Generate FluxCD manifests
        uses: panicboat/deploy-actions/flux-generator@main

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "auto: update FluxCD manifests"
          title: "Auto-update FluxCD manifests"
          body: |
            🤖 FluxCD manifests have been automatically updated

            Changes detected in directories.

            - Generated clusters/ directory structure
            - Updated Kustomization and GitRepository resources
            - Ready for FluxCD deployment
          branch: auto-update-fluxcd-manifests
          delete-branch: true
          labels: auto-generated
