apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-service
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./services/develop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  postBuild:
    substitute:
      service_name: "demo-service"
